### PR TITLE
Completed Delete Operation in Profile Page, and finished the WatchList

### PR DESCRIPTION
**Pull request by Baozzz04**
1. Added id_email field in listings, so only items associated with the same email can be updated/deleted
2. Delete button works now, so the listing will be deleted from the database.
3. WatchList page works, if you click on the heart on the Individual Listing page, the listing will be saved to the WatchList.

Next steps:
1. When I click on the heart, the heart does not stay on (fill with red), but just comes back to normal.
2. Edit operation needs an edit page, in which all fields will be automatically filled with information, and if the user wants to change anything, they can edit in the edit page, and update the database.

### CODE REVIEW

**Comment by sophia-hubscher** [comment]
When I click the heart button, I get a 500 Axios error. Do you know what could be causing that? I put the full error at the bottom of this.

https://github.com/sknooyen/UBay/assets/33038334/6d59bee1-38eb-4b82-a8a6-a67abb266453

`AxiosError {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_RESPONSE"config: adapter: (2) ['xhr', 'http']data: "{\"id\":\"d754e7a4-7b77-4c2f-9fa6-4a4a9694ccb2\",env: {FormData: ƒ, Blob: ƒ}headers: AxiosHeaders {Accept: 'application/json, text/plain, */*', Content-Type: 'application/json'}maxBodyLength: -1maxContentLength: -1method: "post"timeout: 0transformRequest: [ƒ]transformResponse: [ƒ]transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}url: "http://localhost:8000/api/favorite"validateStatus: ƒ validateStatus(status)xsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"[[Prototype]]: Objectmessage: "Request failed with status code 500"name: "AxiosError"request: XMLHttpRequestonabort: ƒ handleAbort()onerror: ƒ handleError()onload: nullonloadend: ƒ onloadend()onloadstart: nullonprogress: nullonreadystatechange: nullontimeout: ƒ handleTimeout()readyState: 4response: "{\"errorResponse\":{\"index\":0,\"code\":11000,\"errmsg\":\"E11000 duplicate key error collection: test.favorites index: id_1 dup key: { id: \\\"d754e7a4-7b77-4c2f-9fa6-4a4a9694ccb2\\\" }\",\"keyPattern\":{\"id\":1},\"keyValue\":{\"id\":\"d754e7a4-7b77-4c2f-9fa6-4a4a9694ccb2\"}},\"index\":0,\"code\":11000,\"keyPattern\":{\"id\":1},\"keyValue\":{\"id\":\"d754e7a4-7b77-4c2f-9fa6-4a4a9694ccb2\"}}"responseText: "{\"errorResponse\":{\"index\":0,\"code\":11000,\"errmsg\":\"E11000 duplicate key error collection: test.favorites index: id_1 dup key: { id: \\\"d754e7a4-7b77-4c2f-9fa6-4a4a9694ccb2\\\" }\",\"keyPattern\":{\"id\":1},\"keyValue\":{\"id\":\"d754e7a4-7b77-4c2f-9fa6-4a4a9694ccb2\"}},\"index\":0,\"code\":11000,\"keyPattern\":{\"id\":1},\"keyValue\":{\"id\":\"d754e7a4-7b77-4c2f-9fa6-4a4a9694ccb2\"}}"responseType: ""responseURL: "http://localhost:8000/api/favorite"responseXML: nullstatus: 500statusText: "Internal Server Error"timeout: 0upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}withCredentials: false[[Prototype]]: XMLHttpRequestresponse: config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}data: {errorResponse: {…}, index: 0, code: 11000, keyPattern: {…}, keyValue: {…}}headers: AxiosHeaders {content-length: '358', content-type: 'application/json; charset=utf-8'}request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}status: 500statusText: "Internal Server Error"[[Prototype]]: Objectstack: "AxiosError: Request failed with status code 500\n    at settle (http://localhost:3000/static/js/bundle.js:99612:12)\n    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:98272:66)\n    at Axios.request (http://localhost:3000/static/js/bundle.js:98773:41)"[[Prototype]]: Errorconstructor: ƒ AxiosError(message, code, config, request, response)toJSON: ƒ toJSON()isAxiosError: true[[Prototype]]: Object`

**Comment by Baozzz04** [comment]
I fixed the error you described above. Can you check again?

**Comment by sophia-hubscher** [comment]
Nice! I'm not getting the error anymore! Side note: We want clicking the button when the heart is red to remove the listing from the user's watchlist. Is there a function we can call to do that?

**Comment by Baozzz04** [comment]
Yes, there is an API call for that, and after we finish the front-end, I will make a separate branch for that. That one will be fast to implement, so don't worry

**Comment by sophia-hubscher** [comment]
Ok, awesome! I'll go ahead and merge

**Pull request merged**
